<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Attendance Scanner') }}
        </h2>
    </x-slot>

    <div class="py-6 sm:py-8">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl rounded-lg p-4 sm:p-6">
                <!-- Instructions -->
                <div class="mb-6 p-4 bg-blue-100 dark:bg-blue-900/30 border border-blue-200 dark:border-blue-700 rounded-md">
                    <h3 class="text-lg font-medium text-blue-800 dark:text-blue-200 mb-2">Attendance Scanner Instructions</h3>
                    <ul class="list-disc pl-5 text-sm text-blue-700 dark:text-blue-300 space-y-1">
                        <li>Select the class and date for attendance</li>
                        <li>Have students present their student QR code (generated from their profile) for scanning</li>
                        <li>Use camera scanner, upload QR image, or enter QR code manually</li>
                        <li>Attendance will be recorded automatically</li>
                    </ul>
                    <p class="mt-2 text-sm text-blue-700 dark:text-blue-300">
                        <strong>Note:</strong> Only QR codes generated by this system will work. Students can access their QR code from their profile page.
                    </p>
                    <div class="mt-3 text-xs text-blue-700 dark:text-blue-300">
                        <p><strong>Troubleshooting:</strong></p>
                        <ul class="list-disc pl-5 space-y-1">
                            <li>Ensure good lighting when scanning</li>
                            <li>Hold the device steady and at proper distance (15-30cm)</li>
                            <li>Make sure the QR code is completely visible on the screen</li>
                            <li>Try the "Full QR View" for larger QR code display</li>
                            <li>Use "Upload QR from Device" if camera scanning fails</li>
                        </ul>
                    </div>
                </div>

                <!-- Instructions for admin to select the correct date -->
                <div class="mb-6 p-4 bg-yellow-100 dark:bg-yellow-900/30 border border-yellow-200 dark:border-yellow-700 rounded-md">
                    <h3 class="text-lg font-medium text-yellow-800 dark:text-yellow-200 mb-2">Class Selection</h3>
                    <p class="text-sm text-yellow-700 dark:text-yellow-300">
                        Students will be automatically matched to their assigned class.
                        Please ensure the date is correct for the class session.
                    </p>
                </div>

                <div class="mb-6">
                    <label for="dateInput" class="block text-sm font-medium text-gray-700">Select Date</label>
                    <input type="date" id="dateInput" name="date" class="mt-1 block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" value="{{ date('Y-m-d') }}">
                </div>

                <div class="mb-6 flex flex-col sm:flex-row sm:space-x-4 space-y-2 sm:space-y-0">
                    <button id="startScannerBtn" class="bg-blue-500 hover:bg-blue-700 text-black font-bold py-3 px-4 rounded-lg flex-1 text-sm sm:text-base">
                        Scan Student QR Code
                    </button>
                    <button id="uploadQRBtn" class="bg-green-500 hover:bg-green-700 text-black font-bold py-3 px-4 rounded-lg flex-1 text-sm sm:text-base">
                        Upload QR from Device
                    </button>
                    <button id="manualInputBtn" class="bg-gray-500 hover:bg-gray-700 text-black font-bold py-3 px-4 rounded-lg flex-1 text-sm sm:text-base">
                        Manual QR Input
                    </button>
                </div>

                <div class="mb-6" id="uploadContainer" style="display:none;">
                    <h3 class="text-lg font-medium text-gray-900 dark:text-white mb-2">Upload QR Code Image</h3>
                    <div class="flex flex-col sm:flex-row sm:space-x-4 space-y-2 sm:space-y-0">
                        <input type="file" id="qrImageUpload" accept="image/*" class="flex-1 px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:rounded-r-none sm:rounded-l-md">
                        <button id="processUploadBtn" class="bg-indigo-600 hover:bg-indigo-700 text-white px-4 py-2 rounded-md sm:rounded-l-none sm:rounded-r-md mt-2 sm:mt-0">
                            Process
                        </button>
                    </div>
                </div>

                <div class="mb-6" id="scannerContainer" style="display:none;">
                    <h3 class="text-lg font-medium text-gray-900 mb-2">Camera Scanner</h3>
                    <div class="flex flex-col items-center">
                        <video id="video" width="100%" max-width="300" height="200" class="max-w-full h-auto" style="border: 1px solid #ccc;"></video>
                        <canvas id="canvas" style="display: none;"></canvas>
                        <button id="captureBtn" class="mt-2 bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded-lg" style="display: none;">Capture</button>
                        <p id="scannerStatus" class="mt-2 text-sm text-gray-600">Point camera at QR code</p>
                    </div>
                </div>

                <div class="mb-6" id="manualInputContainer" style="display:none;">
                    <h3 class="text-lg font-medium text-gray-900 mb-2">Manual QR Code Input</h3>
                    <div class="flex flex-col sm:flex-row sm:space-x-0 space-y-2 sm:space-y-0">
                        <input type="text" id="qrInput" placeholder="Enter QR code data" class="flex-1 px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:rounded-r-none sm:rounded-l-md">
                        <button id="submitQRBtn" class="bg-indigo-600 hover:bg-indigo-700 text-white px-4 py-2 rounded-lg sm:rounded-l-none sm:rounded-r-md mt-2 sm:mt-0">
                            Process
                        </button>
                    </div>
                </div>

                <div class="mb-6" id="resultContainer" style="display:none;">
                    <h3 class="text-lg font-medium text-gray-900 mb-2">Scan Result</h3>
                    <div id="result" class="bg-gray-100 p-4 rounded-md"></div>
                </div>

                <!-- Attendance Status Selection Modal -->
                <div id="statusModal" class="fixed inset-0 bg-gray-600 bg-opacity-50 overflow-y-auto h-full w-full hidden z-50">
                    <div class="relative top-20 mx-auto p-5 border w-full max-w-md shadow-lg rounded-md bg-white">
                        <div class="mt-3 text-center">
                            <h3 class="text-lg font-medium text-gray-900 mb-4" id="statusModalTitle">Select Attendance Status</h3>
                            <div class="flex flex-col space-y-2 mb-4">
                                <div id="studentInfo" class="text-left mb-4"></div>
                                <div class="grid grid-cols-2 gap-2">
                                    <button type="button" id="statusPresent" class="bg-green-500 hover:bg-green-600 text-black font-bold py-2 px-4 rounded text-sm">
                                        Hadir
                                    </button>
                                    <button type="button" id="statusLate" class="bg-yellow-500 hover:bg-yellow-600 text-black font-bold py-2 px-4 rounded text-sm">
                                        Izin
                                    </button>
                                    <button type="button" id="statusAbsent" class="bg-red-500 hover:bg-red-600 text-black font-bold py-2 px-4 rounded text-sm">
                                        Alpha
                                    </button>
                                    <button type="button" id="statusSick" class="bg-blue-500 hover:bg-blue-600 text-black font-bold py-2 px-4 rounded text-sm">
                                        Sakit
                                    </button>
                                </div>
                            </div>
                            <p class="text-xs text-gray-500 mt-2">Choose the appropriate attendance status for the student</p>
                        </div>
                    </div>
                </div>

                <div id="attendanceTable" class="overflow-x-auto" style="display:none;">
                    <h3 class="text-lg font-medium text-gray-900 mb-4">Today's Attendance</h3>
                    <table class="min-w-full divide-y divide-gray-200 sm:rounded-lg overflow-hidden">
                        <thead class="bg-gray-50">
                            <tr>
                                <th scope="col" class="px-3 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider sm:px-6 sm:py-3">Student</th>
                                <th scope="col" class="px-3 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider sm:px-6 sm:py-3">Class</th>
                                <th scope="col" class="px-3 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider sm:px-6 sm:py-3">Check-in Time</th>
                                <th scope="col" class="px-3 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider sm:px-6 sm:py-3">Status</th>
                                <th scope="col" class="px-3 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider sm:px-6 sm:py-3">Notes</th>
                            </tr>
                        </thead>
                        <tbody class="bg-white divide-y divide-gray-200" id="attendanceTableBody">
                            <!-- Attendance records will be populated here -->
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <!-- Include jsQR for QR code scanning -->
    <script src="https://cdn.jsdelivr.net/npm/jsqr@1.4.0/dist/jsQR.min.js"></script>

    <style>
        /* Custom toast notification styles */
        .toast {
            position: fixed;
            top: 20px;
            right: 20px;
            padding: 16px 24px;
            border-radius: 8px;
            color: white;
            font-weight: 500;
            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
            z-index: 9999;
            display: flex;
            align-items: center;
            min-width: 300px;
            transform: translateX(400px);
            transition: transform 0.3s ease-in-out;
        }

        .toast.show {
            transform: translateX(0);
        }

        .toast.success {
            background-color: #10b981;
        }

        .toast.error {
            background-color: #ef4444;
        }

        .toast.info {
            background-color: #3b82f6;
        }

        .toast-content {
            flex: 1;
        }

        .toast-close {
            background: none;
            border: none;
            color: white;
            font-size: 1.5rem;
            cursor: pointer;
            margin-left: 12px;
        }
    </style>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const classSelect = document.getElementById('classSelect');
            const dateInput = document.getElementById('dateInput');
            const startScannerBtn = document.getElementById('startScannerBtn');
            const uploadQRBtn = document.getElementById('uploadQRBtn');
            const manualInputBtn = document.getElementById('manualInputBtn');
            const scannerContainer = document.getElementById('scannerContainer');
            const uploadContainer = document.getElementById('uploadContainer');
            const manualInputContainer = document.getElementById('manualInputContainer');
            const captureBtn = document.getElementById('captureBtn');
            const video = document.getElementById('video');
            const canvas = document.getElementById('canvas');
            const qrImageUpload = document.getElementById('qrImageUpload');
            const processUploadBtn = document.getElementById('processUploadBtn');
            const qrInput = document.getElementById('qrInput');
            const submitQRBtn = document.getElementById('submitQRBtn');
            const resultContainer = document.getElementById('resultContainer');
            const resultDiv = document.getElementById('result');
            const attendanceTable = document.getElementById('attendanceTable');
            const attendanceTableBody = document.getElementById('attendanceTableBody');
            const scannerStatus = document.getElementById('scannerStatus');

            // When date changes, fetch attendance (no class selection needed anymore)
            dateInput.addEventListener('change', fetchAttendance);

            // Show manual input form
            manualInputBtn.addEventListener('click', function() {
                if (!dateInput.value) {
                    alert('Please select a date first');
                    return;
                }

                manualInputContainer.style.display = 'block';
                scannerContainer.style.display = 'none';
                uploadContainer.style.display = 'none';
            });

            // Show upload form
            uploadQRBtn.addEventListener('click', function() {
                if (!dateInput.value) {
                    alert('Please select a date first');
                    return;
                }

                scannerContainer.style.display = 'none';
                manualInputContainer.style.display = 'none';
                uploadContainer.style.display = 'block';
            });

            // Process uploaded QR image
            processUploadBtn.addEventListener('click', function() {
                const file = qrImageUpload.files[0];
                if (!file) {
                    resultDiv.innerHTML = '<p class="text-red-600">Please select a QR code image file</p>';
                    resultContainer.style.display = 'block';
                    return;
                }

                // Check if the file is an image
                if (!file.type.match('image.*')) {
                    resultDiv.innerHTML = '<p class="text-red-600">Please select an image file (JPEG, PNG, etc.)</p>';
                    resultContainer.style.display = 'block';
                    return;
                }

                // Show loading indicator
                resultDiv.innerHTML = '<p class="text-blue-600">Processing image, please wait...</p>';
                resultContainer.style.display = 'block';

                const reader = new FileReader();
                reader.onload = function(e) {
                    const img = new Image();
                    img.onload = function() {
                        // Create a canvas to draw the image and scan for QR codes
                        const canvas = document.createElement('canvas');
                        const ctx = canvas.getContext('2d');

                        // Calculate optimal dimensions to speed up processing
                        const maxWidth = 800;
                        const maxHeight = 600;
                        let { width, height } = img;

                        // Calculate aspect ratio to maintain image proportions
                        if (width > maxWidth) {
                            height = (height * maxWidth) / width;
                            width = maxWidth;
                        }
                        if (height > maxHeight) {
                            width = (width * maxHeight) / height;
                            height = maxHeight;
                        }

                        canvas.width = width;
                        canvas.height = height;
                        ctx.drawImage(img, 0, 0, width, height);

                        const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height);
                        const code = jsQR(imageData.data, imageData.width, imageData.height);

                        if (code) {
                            // Check if code.data is not empty before processing
                            if (code.data && code.data.trim() !== '') {
                                resultDiv.innerHTML = '<p>Scanned: ' + code.data + '</p>';
                                console.log('Uploaded QR data:', code.data); // Debug log
                                processScan(code.data);
                            } else {
                                resultDiv.innerHTML = '<p class="text-orange-600">QR detected in image but data is empty. Please try another image with a valid student QR code.</p>';
                            }
                        } else {
                            resultDiv.innerHTML = '<p class="text-red-600">No QR code detected in the uploaded image. Please try another image.</p>';
                        }
                    };
                    img.src = e.target.result;
                };
                reader.readAsDataURL(file);
            });

            // Initialize camera scanner
            startScannerBtn.addEventListener('click', function() {
                if (!dateInput.value) {
                    alert('Please select a date first');
                    return;
                }

                manualInputContainer.style.display = 'none';
                uploadContainer.style.display = 'none';
                scannerContainer.style.display = 'block';
                initCameraScanner();
            });

            // Submit manually entered QR code
            submitQRBtn.addEventListener('click', function() {
                const qrData = qrInput.value.trim();
                if (!qrData) {
                    resultDiv.innerHTML = '<p class="text-red-600">Please enter QR code data</p>';
                    resultContainer.style.display = 'block';
                    return;
                }

                processScan(qrData);
            });

            // Process QR code when captured
            captureBtn.addEventListener('click', function() {
                const videoWidth = video.videoWidth;
                const videoHeight = video.videoHeight;

                // Use optimized dimensions for capture
                const maxWidth = 800;
                const maxHeight = 600;
                let width = videoWidth;
                let height = videoHeight;

                // Calculate aspect ratio to maintain image proportions
                if (width > maxWidth) {
                    height = (height * maxWidth) / width;
                    width = maxWidth;
                }
                if (height > maxHeight) {
                    width = (width * maxHeight) / height;
                    height = maxHeight;
                }

                canvas.width = width;
                canvas.height = height;

                const context = canvas.getContext('2d');
                context.drawImage(video, 0, 0, canvas.width, canvas.height);

                const imageData = context.getImageData(0, 0, canvas.width, canvas.height);
                const code = jsQR(imageData.data, imageData.width, imageData.height);

                if (code) {
                    console.log('Raw QR code data:', code.data); // Debug log
                    // Check if code.data is not empty before processing
                    if (code.data && code.data.trim() !== '') {
                        resultDiv.innerHTML = '<p>Scanned: ' + code.data + '</p>';
                        resultContainer.style.display = 'block';
                        processScan(code.data);
                    } else {
                        resultDiv.innerHTML = '<p class="text-orange-600">QR detected but data is empty. Please try again with a valid student QR code.</p>';
                        resultContainer.style.display = 'block';
                    }
                } else {
                    resultDiv.innerHTML = '<p class="text-red-600">No QR code detected. Please try again.</p>';
                    resultContainer.style.display = 'block';
                }
            });

            function initCameraScanner() {
                if (navigator.mediaDevices && navigator.mediaDevices.getUserMedia) {
                    navigator.mediaDevices.getUserMedia({ video: { facingMode: "environment" } })
                        .then(function(stream) {
                            video.srcObject = stream;
                            video.setAttribute("playsinline", true); // required to tell iOS safari we don't want fullscreen
                            video.play();
                            scannerStatus.textContent = 'Camera active - Point at QR code';

                            // Start QR code detection
                            requestAnimationFrame(tick);
                        })
                        .catch(function(err) {
                            console.error("Error accessing camera: ", err);
                            resultDiv.innerHTML = '<p class="text-red-600">Error accessing camera: ' + err.message + '</p>';
                            resultContainer.style.display = 'block';
                        });
                } else {
                    resultDiv.innerHTML = '<p class="text-red-600">Camera not supported in this browser</p>';
                    resultContainer.style.display = 'block';
                }
            }

            function tick() {
                if (video.readyState === video.HAVE_ENOUGH_DATA) {
                    // Use smaller canvas dimensions for faster processing
                    const videoWidth = video.videoWidth;
                    const videoHeight = video.videoHeight;

                    // Only resize canvas if it's significantly different from video dimensions
                    if (canvas.width !== videoWidth || canvas.height !== videoHeight) {
                        // Calculate optimal dimensions to speed up processing
                        const maxWidth = 640;  // Smaller than before for faster processing
                        const maxHeight = 480;
                        let width = videoWidth;
                        let height = videoHeight;

                        // Calculate aspect ratio to maintain image proportions
                        if (width > maxWidth) {
                            height = (height * maxWidth) / width;
                            width = maxWidth;
                        }
                        if (height > maxHeight) {
                            width = (width * maxHeight) / height;
                            height = maxHeight;
                        }

                        canvas.width = width;
                        canvas.height = height;
                    }

                    const context = canvas.getContext('2d');
                    context.drawImage(video, 0, 0, canvas.width, canvas.height);
                    const imageData = context.getImageData(0, 0, canvas.width, canvas.height);
                    const code = jsQR(imageData.data, imageData.width, imageData.height);

                    if (code) {
                        // Highlight the QR code area
                        context.lineWidth = 2;
                        context.strokeStyle = "#00FF00";
                        // Adjust highlight position based on scaled coordinates
                        const scaleX = canvas.width / videoWidth;
                        const scaleY = canvas.height / videoHeight;
                        context.strokeRect(
                            code.location.topLeftCorner.x * scaleX,
                            code.location.topLeftCorner.y * scaleY,
                            (code.location.topRightCorner.x - code.location.topLeftCorner.x) * scaleX,
                            (code.location.bottomRightCorner.y - code.location.topLeftCorner.y) * scaleY
                        );

                        console.log('Raw QR code data:', code.data); // Debug log
                        // Check if code.data is not empty before processing
                        if (code.data && code.data.trim() !== '') {
                            // Display captured code
                            resultDiv.innerHTML = '<p>Scanned: ' + code.data + '</p>';
                            resultContainer.style.display = 'block';
                            captureBtn.style.display = 'block';

                            console.log('Detected QR data:', code.data); // Debug log

                            // Process the QR code immediately
                            processScan(code.data);
                        } else {
                            resultDiv.innerHTML = '<p class="text-orange-600">QR detected but data is empty. Please try again with a valid student QR code.</p>';
                            resultContainer.style.display = 'block';
                            captureBtn.style.display = 'none';
                        }
                    } else {
                        captureBtn.style.display = 'none';
                    }
                }
                requestAnimationFrame(tick);
            }

            function processScan(qrData) {
                // Only proceed if qrData is not empty
                if (!qrData || qrData.trim() === '') {
                    resultDiv.innerHTML = '<p class="text-red-600">Error: No QR code data detected. Please make sure the QR code is properly positioned.</p>';
                    resultContainer.style.display = 'block';
                    return;
                }

                // Try to parse the QR data as JSON to verify it's in the expected format
                try {
                    const parsedData = JSON.parse(qrData);
                    console.log('Parsed QR data:', parsedData); // Debug log
                } catch (e) {
                    resultDiv.innerHTML = '<p class="text-red-600">Error: Invalid QR code format. Please use a valid student QR code from the system.</p>';
                    resultContainer.style.display = 'block';
                    console.error('QR data parsing error:', e);
                    return;
                }

                // Show validation indicator
                resultDiv.innerHTML = '<p class="text-blue-600">Validating QR code data...</p>';

                fetch('/attendance/process-scan', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]').getAttribute('content')
                    },
                    body: JSON.stringify({
                        qr_data: qrData,
                        date: dateInput.value
                    })
                })
                .then(response => response.json())
                .then(data => {
                    if (data.success) {
                        resultDiv.innerHTML += '<p class="text-green-600">' + data.message + '</p>';
                        if (data.student) {
                            resultDiv.innerHTML += '<p class="text-blue-600">Student: ' + data.student.name + ' (' + data.student.email + ')</p>';
                        } else if (data.admin) {
                            resultDiv.innerHTML += '<p class="text-blue-600">Admin: ' + data.admin.name + ' (' + data.admin.email + ')</p>';
                        }
                        // Refresh attendance list
                        fetchAttendance();
                    } else if (data.show_status_modal) {
                        // Show the status selection modal to allow changing status
                        resultDiv.innerHTML += '<p class="text-green-600">' + data.message + '</p>';
                        if (data.student) {
                            resultDiv.innerHTML += '<p class="text-blue-600">Student: ' + data.student.name + ' (' + data.student.email + ') - Current Status: ' + data.current_status + '</p>';
                        } else if (data.admin) {
                            resultDiv.innerHTML += '<p class="text-blue-600">Admin: ' + data.admin.name + ' (' + data.admin.email + ') - Current Status: ' + data.current_status + '</p>';
                        }

                        // Determine if this is a student or admin for the modal
                        const isStudent = !!data.student;
                        const userData = isStudent ? data.student : data.admin;

                        document.getElementById('studentInfo').innerHTML =
                            '<p class="font-medium">' + (isStudent ? 'Student' : 'Admin') + ': <strong>' + userData.name + '</strong></p>' +
                            '<p>Email: ' + userData.email + '</p>' +
                            '<p>Class: ' + (userData.class || 'N/A') + '</p>' +
                            '<p>Current Status: <span id="currentStatus" class="font-bold">' + data.current_status.toUpperCase() + '</span></p>';

                        // Store the QR data and date for later use
                        window.currentQRData = qrData;
                        window.currentDate = dateInput.value;
                        window.currentStudentId = userData.id; // This should work for both student and admin

                        // Show the status modal
                        document.getElementById('statusModal').style.display = 'block';

                        // Refresh attendance list
                        fetchAttendance();
                    } else {
                        resultDiv.innerHTML += '<p class="text-red-600">Error: ' + data.message + '</p>';
                        if (data.message.includes('Invalid QR code')) {
                            resultDiv.innerHTML += '<p class="text-sm text-gray-600 mt-2">Make sure you are scanning a valid student QR code generated from the system.</p>';
                        }
                    }
                })
                .catch(error => {
                    resultDiv.innerHTML += '<p class="text-red-600">Error: ' + error.message + '</p>';
                    console.error('Scan error:', error);
                });
            }

            function fetchAttendance() {
                if (!dateInput.value) {
                    return;
                }

                // For now, we'll fetch all attendance for the selected date
                // In a real implementation, you might want to show attendance for all classes or filter differently
                fetch('/attendance/get', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]').getAttribute('content')
                    },
                    body: JSON.stringify({
                        date: dateInput.value
                    })
                })
                .then(response => response.json())
                .then(data => {
                    if (data.attendances && data.attendances.length > 0) {
                        attendanceTable.style.display = 'block';
                        attendanceTableBody.innerHTML = '';

                        data.attendances.forEach(attendance => {
                            const row = document.createElement('tr');

                            // Create and append cells safely to prevent XSS
                            const nameCell = document.createElement('td');
                            nameCell.className = 'px-3 py-3 sm:px-6 sm:py-4 whitespace-nowrap text-sm text-gray-900';
                            nameCell.textContent = attendance.user.name;

                            const classCell = document.createElement('td');
                            classCell.className = 'px-3 py-3 sm:px-6 sm:py-4 whitespace-nowrap text-sm text-gray-500';
                            classCell.textContent = attendance.schedule?.classModel?.name || 'N/A';

                            const timeCell = document.createElement('td');
                            timeCell.className = 'px-3 py-3 sm:px-6 sm:py-4 whitespace-nowrap text-sm text-gray-500';
                            timeCell.textContent = attendance.check_in_time ? new Date(attendance.check_in_time).toLocaleTimeString() : 'N/A';

                            const statusCell = document.createElement('td');
                            statusCell.className = 'px-3 py-3 sm:px-6 sm:py-4 whitespace-nowrap text-sm text-gray-500';

                            const statusSpan = document.createElement('span');
                            statusSpan.className = 'px-2 inline-flex text-xs leading-5 font-semibold rounded-full';

                            // Set status-specific classes
                            if (attendance.status === 'present') {
                                statusSpan.className += ' bg-green-100 text-green-800';
                            } else if (attendance.status === 'late') {
                                statusSpan.className += ' bg-yellow-100 text-yellow-800';
                            } else if (attendance.status === 'absent') {
                                statusSpan.className += ' bg-red-100 text-red-800';
                            } else {
                                statusSpan.className += ' bg-blue-100 text-blue-800';
                            }

                            statusSpan.textContent = attendance.status.charAt(0).toUpperCase() + attendance.status.slice(1);
                            statusCell.appendChild(statusSpan);

                            const notesCell = document.createElement('td');
                            notesCell.className = 'px-3 py-3 sm:px-6 sm:py-4 whitespace-nowrap text-sm text-gray-500';
                            notesCell.textContent = attendance.notes || '';

                            row.appendChild(nameCell);
                            row.appendChild(classCell);
                            row.appendChild(timeCell);
                            row.appendChild(statusCell);
                            row.appendChild(notesCell);

                            attendanceTableBody.appendChild(row);
                        });
                    } else {
                        attendanceTable.style.display = 'block';
                        attendanceTableBody.innerHTML = `
                            <tr>
                                <td colspan="5" class="px-6 py-4 text-center text-sm text-gray-500">
                                    No attendance records found for this date.
                                </td>
                            </tr>
                        `;
                    }
                })
                .catch(error => {
                    console.error('Error:', error);
                });
            }

            // Event listeners for attendance status buttons
            document.getElementById('statusPresent').addEventListener('click', function() {
                selectAttendanceStatus('present');
            });

            document.getElementById('statusLate').addEventListener('click', function() {
                selectAttendanceStatus('excused'); // Using 'excused' for 'Izin'
            });

            document.getElementById('statusAbsent').addEventListener('click', function() {
                selectAttendanceStatus('absent');
            });

            document.getElementById('statusSick').addEventListener('click', function() {
                selectAttendanceStatus('sick'); // We'll handle 'sick' as its own status
            });

            function selectAttendanceStatus(status) {
                document.getElementById('statusModal').style.display = 'none';

                // Get student data from the modal
                const studentName = document.querySelector('#studentInfo .font-medium strong').textContent;

                // Show processing message
                resultDiv.innerHTML = '<p class="text-blue-600">Updating attendance for ' + studentName + ' status to ' + status.toUpperCase() + '...</p>';
                resultContainer.style.display = 'block';

                // First, find the schedule for the student on the given date
                fetch('/attendance/get', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]').getAttribute('content')
                    },
                    body: JSON.stringify({
                        date: window.currentDate,
                        user_id: window.currentStudentId  // Only get this student's attendance
                    })
                })
                .then(response => response.json())
                .then(scheduleData => {
                    if (scheduleData.attendances && scheduleData.attendances.length > 0) {
                        const attendanceId = scheduleData.attendances[0].id;
                        // Update the existing attendance record
                        fetch('/attendance/store', {
                            method: 'POST',
                            headers: {
                                'Content-Type': 'application/json',
                                'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]').getAttribute('content')
                            },
                            body: JSON.stringify({
                                user_id: window.currentStudentId,
                                schedule_id: scheduleData.attendances[0].schedule_id,
                                status: status,  // Update to the selected status
                                notes: scheduleData.attendances[0].notes || ''
                            })
                        })
                        .then(response => response.json())
                        .then(updateData => {
                            if (updateData.success) {
                                resultDiv.innerHTML = '<p class="text-green-600">Attendance status updated successfully to ' + status.toUpperCase() + '</p>';
                                if (updateData.attendance) {
                                    resultDiv.innerHTML += '<p class="text-blue-600">New Status: ' + updateData.attendance.status.toUpperCase() + '</p>';
                                }
                            } else {
                                resultDiv.innerHTML += '<p class="text-red-600">Error updating status: ' + updateData.message + '</p>';
                            }
                            // Refresh attendance list
                            fetchAttendance();
                        })
                        .catch(error => {
                            resultDiv.innerHTML += '<p class="text-red-600">Error updating attendance: ' + error.message + '</p>';
                            console.error('Update attendance error:', error);
                        });
                    } else {
                        resultDiv.innerHTML += '<p class="text-red-600">Error: Could not find attendance record to update</p>';
                    }
                })
                .catch(error => {
                    resultDiv.innerHTML += '<p class="text-red-600">Error finding attendance: ' + error.message + '</p>';
                    console.error('Find attendance error:', error);
                });
            }

            // Close modal if clicked outside
            window.onclick = function(event) {
                const modal = document.getElementById('statusModal');
                if (event.target === modal) {
                    modal.style.display = 'none';
                }
            }

            // Create and show toast notification
            function showToast(message, type = 'success') {
                // Remove any existing toasts
                const existingToast = document.querySelector('.toast');
                if (existingToast) {
                    existingToast.remove();
                }

                // Create toast element
                const toast = document.createElement('div');
                toast.className = `toast ${type}`;
                toast.innerHTML = `
                    <div class="toast-content">${message}</div>
                    <button class="toast-close">&times;</button>
                `;

                document.body.appendChild(toast);

                // Show toast
                setTimeout(() => {
                    toast.classList.add('show');
                }, 100);

                // Auto-hide after 5 seconds
                setTimeout(() => {
                    toast.classList.remove('show');
                    setTimeout(() => {
                        if (toast.parentNode) {
                            toast.parentNode.removeChild(toast);
                        }
                    }, 300);
                }, 5000);

                // Add close event
                toast.querySelector('.toast-close').addEventListener('click', () => {
                    toast.classList.remove('show');
                    setTimeout(() => {
                        if (toast.parentNode) {
                            toast.parentNode.removeChild(toast);
                        }
                    }, 300);
                });
            }

            // Enhanced processScan function with notifications
            function processScan(qrData) {
                // Only proceed if qrData is not empty
                if (!qrData || qrData.trim() === '') {
                    resultDiv.innerHTML = '<p class="text-red-600">Error: No QR code data detected. Please make sure the QR code is properly positioned.</p>';
                    resultContainer.style.display = 'block';
                    showToast('No QR code data detected. Please try again.', 'error');
                    return;
                }

                // Try to parse the QR data as JSON to verify it's in the expected format
                try {
                    const parsedData = JSON.parse(qrData);
                    console.log('Parsed QR data:', parsedData); // Debug log
                } catch (e) {
                    resultDiv.innerHTML = '<p class="text-red-600">Error: Invalid QR code format. Please use a valid student QR code from the system.</p>';
                    resultContainer.style.display = 'block';
                    console.error('QR data parsing error:', e);
                    showToast('Invalid QR code format. Please try again.', 'error');
                    return;
                }

                // Show validation indicator
                resultDiv.innerHTML = '<p class="text-blue-600">Validating QR code data...</p>';

                fetch('/attendance/process-scan', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]').getAttribute('content')
                    },
                    body: JSON.stringify({
                        qr_data: qrData,
                        date: dateInput.value
                    })
                })
                .then(response => response.json())
                .then(data => {
                    if (data.success) {
                        resultDiv.innerHTML += '<p class="text-green-600">' + data.message + '</p>';
                        if (data.student) {
                            resultDiv.innerHTML += '<p class="text-blue-600">Student: ' + data.student.name + ' (' + data.student.email + ')</p>';
                        } else if (data.admin) {
                            resultDiv.innerHTML += '<p class="text-blue-600">Admin: ' + data.admin.name + ' (' + data.admin.email + ')</p>';
                        }

                        // Show success notification
                        const studentName = data.student ? data.student.name : (data.admin ? data.admin.name : 'Unknown');
                        showToast(`Attendance recorded successfully for ${studentName}!`, 'success');

                        // Refresh attendance list
                        fetchAttendance();
                    } else if (data.show_status_modal) {
                        // Show the status selection modal to allow changing status
                        resultDiv.innerHTML += '<p class="text-green-600">' + data.message + '</p>';
                        if (data.student) {
                            resultDiv.innerHTML += '<p class="text-blue-600">Student: ' + data.student.name + ' (' + data.student.email + ') - Current Status: ' + data.current_status + '</p>';
                        } else if (data.admin) {
                            resultDiv.innerHTML += '<p class="text-blue-600">Admin: ' + data.admin.name + ' (' + data.admin.email + ') - Current Status: ' + data.current_status + '</p>';
                        }

                        // Determine if this is a student or admin for the modal
                        const isStudent = !!data.student;
                        const userData = isStudent ? data.student : data.admin;

                        document.getElementById('studentInfo').innerHTML =
                            '<p class="font-medium">' + (isStudent ? 'Student' : 'Admin') + ': <strong>' + userData.name + '</strong></p>' +
                            '<p>Email: ' + userData.email + '</p>' +
                            '<p>Class: ' + (userData.class || 'N/A') + '</p>' +
                            '<p>Current Status: <span id="currentStatus" class="font-bold">' + data.current_status.toUpperCase() + '</span></p>';

                        // Store the QR data and date for later use
                        window.currentQRData = qrData;
                        window.currentDate = dateInput.value;
                        window.currentStudentId = userData.id; // This should work for both student and admin

                        // Show the status modal
                        document.getElementById('statusModal').style.display = 'block';

                        // Show notification that status selection is required
                        showToast(`QR scanned for ${userData.name}. Please select attendance status.`, 'info');

                        // Refresh attendance list
                        fetchAttendance();
                    } else {
                        resultDiv.innerHTML += '<p class="text-red-600">Error: ' + data.message + '</p>';
                        if (data.message.includes('Invalid QR code')) {
                            resultDiv.innerHTML += '<p class="text-sm text-gray-600 mt-2">Make sure you are scanning a valid student QR code generated from the system.</p>';
                        }

                        showToast(data.message, 'error');
                    }
                })
                .catch(error => {
                    resultDiv.innerHTML += '<p class="text-red-600">Error: ' + error.message + '</p>';
                    console.error('Scan error:', error);
                    showToast('Connection error. Please try again.', 'error');
                });
            }
        });
    </script>
</x-app-layout>